config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
    }
   
  resources :events
  get 'users/:id', to: 'users#show', as: 'user'
  # resources :guest_lists
  # POST 'guest_lists/create.:event_id', to: 'guest_lists#create'
  post 'events/add_attendee/:id', to: 'events#add_attendee', as: 'add_attendee'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
  has_one :guest_list
  has_many :attendees, :through => :guest_list, :source => :user
  # has_many :attendees, through: :guest_list, source: :users

  scope :past, -> { where('event_date < ?', Date.today) }
  scope :upcoming, -> { where('event_date >= ?', Date.today) }

end

app/models/guest_list.rb
class GuestList < ApplicationRecord
  belongs_to :event, :foreign_key => 'event_id'
  belongs_to :user, :foreign_key => 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :events, :foreign_key => "creator_id", :class_name => "Event"
  has_many :guest_lists
  has_many :attended_events, :through => :guest_lists, source: :event
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /dmeets or /dmeets.json
   

  def index
    @upcoming_events = Event.upcoming.order("event_date")
    @past_events = Event.past.order("event_date DESC")
    @event = Event.new
  end

  # GET /dmeets/1 or /dmeets/1.json
  def show
    @event = Event.find(params[:id])
  end

  def add_attendee
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.attendees.include?(current_user)
        format.html { redirect_to event_path(@event), notice: 'you are already attending this event.'}
      else
        @guests = GuestList.new
        @guests.user_id = current_user.id
        @guests.event_id = @event.id
        @guests.save
        format.html { redirect_to event_path(@event), notice: 'you are now attending this event.' }
      end  
    end  
  end

  # GET /dmeets/new
  def new
    @event = current_user.events.build
  end

  # GET /dmeets/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /dmeets or /dmeets.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: "event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dmeets/1 or /dmeets/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dmeets/1 or /dmeets/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "event was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :location, :description, :event_date)
    end
end

app/controllers/guest_lists_controller.rb
class GuestListsController < ApplicationController

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @upcoming_events = Event.upcoming.order("event_date")
    @past_events = Event.past.order("event_date")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/guest_list_helper.rb
module GuestListHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_feed.html.erb
<div class='column is-half'>
<h1 class='title is-5'>Upcoming Events</h1>  
  <% @upcoming_events.each do | event | %>
  <div class='box'>
    <article class='media'>
      <div class='media-left'>
        <figure class='image is-64x64'>
          <%= gravatar_image_tag(event.creator.email, size: 64)%>
        </figure>
      </div>
      <div class='media-content'>
        <div class='content'>
          <p class='title is-3'><%= event.title %></p>
          <p class='subtitle is-5'>@<%= event.location %></p>
          <p><%= event.description %></p>
          <p class='date'><%= event.event_date %></p>
          <small>hosted by</small><br />
          <strong><%= event.creator.email %></strong><br />
          <p>attendees <%= event.attendees.count %></p>
          <%= link_to 'see event', event_path(event), method: :get, class: 'button is-info' %>
        </div>
      </div>
    </article> 
  </div>
  <% end %>
</div>     

app/views/events/_form.html.erb
<div class='section'>
  <div class='container'>
  <div class='columns is-centered'>
  <div class='column is-4'>
  <h2 class='title is-2'>New Event</h2>

  <%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

    <div class='field'>
      <div class='control'>
        <%= f.input :title,
                    required: true,
                    input_html: { class: 'input' },
                    wrapper: false,
                    label_html: { class: 'label'} %>
      </div>
    </div>

    <div class='field'>
      <div class='control'>
        <%= f.input :location,
                    required: true,
                    input_html: { class: 'input' },
                    wrapper: false,
                    label_html: { class: 'label'} %>
      </div>
    </div>

    <div class='field'>
      <div class='control'>
        <%= f.input :description,
                    required: true,
                    autofocus: true,
                    input_html: { class: 'textarea ' },
                    wrapper: false,
                    label_html: { class: 'label'} %>
      </div>
    </div>            
    <div class='field'>
      <div class='control'>            
        <%= f.input :event_date,
                    required: true,
                    input_html: { class: 'input' },
                    wrapper: false,
                    label_html: { class: 'label'}  %>
      </div>
    </div>            
    <div class='field'>
      <div class='control'>
        <%= f.button :submit, "submit", class: 'button is-info is-medium' %>
      </div>
    </div>
    <% end %>
    <br />

    

app/views/events/_past.html.erb
<div class='column is-half'>
<h1 class='title is-5'>Past Events</h1>  
  <% @past_events.each do | event | %>
  <div class='box'>
    <article class='media'>
      <div class='media-left'>
        <figure class='image is-64x64'>
          <%= gravatar_image_tag(event.creator.email, size: 64)%>
        </figure>
      </div>
      <div class='media-content'>
        <div class='content'>
          <p class='title is-3'><%= event.title %></p>
          <p class='subtitle is-5'>@<%= event.location %></p>
          <p><%= event.description %></p>
          <p class='date'>occured on <%= event.event_date %></p>
          <small>hosted by</small><br />
          <strong><%= event.creator.email %></strong><br />
          <p><%= event.attendees.count %> guests went</p>
          <%= link_to 'see event', event_path(event), method: :get, class: 'button is-info' %>
        </div>
      </div>
    </article> 
  </div>
  <% end %>
</div>   

app/views/events/index.html.erb
<section class='section'>
  <div class='container'>
    <div class='columns'>
      <%= render 'feed' %>
      <%= render 'past' %>
    </div>
  </div>
</section>    

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
  <div class='container'>
    <div class='columns'>      
      <div class='column is-half'>
      <h1 class='title is-2'><%= @event.title %></h1>
      <p class='subtitle is-5'>@<%= @event.location %></p> 
        <div class='box'>
          <article class='media'>
            <%# <div class='media-left'> %>
              <div class='media-content'>
                <div class='content'>
                  <p><%= @event.description %></p>
                  <p class='date'><%= @event.event_date %></p>
                  <%= button_to 'attend', add_attendee_path(@event), method: :post, class: 'button is-info' %>
                  <small>hosted by</small><br />
                  <strong><%= @event.creator.email %></strong><br />
                </div>
              </div>
            <%# </div> %>
          </article> 
        </div>
      </div>
      <div class='column is-half'>
      <h1 class='title is-2'>attendees</h1>
        <div class='box'>
          <article class='media'>
              <%# <div class='media-right'> %>
              <div class='media-content'>
                <div class='content'>
                  
                  <% @event.attendees.each do | a | %>
                            <%# <figure class='image is-32x32'> %>
                  <p><%= a.email %></p>
                  <%= gravatar_image_tag(a.email, size: 32)%>
                            <%# </figure> %>
                  <% end %>
                </div>     
              </div>
              <%# </div> %>
          </article>
        </div>
      </div>    
    </div>
  </div>
  

app/views/guest_lists/_form.html.erb
<%= simple_form_for(GuestList.new, :url => {:action => "create" })  do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :event_id, :value => (event.id) %>
  <%= f.hidden_field :user_id, :value => (current_user.id) %>
    <div class='field'>
      <div class='control'>
        <%= f.button :submit, "submit", class: 'button is-info is-medium' %>
      </div>
    </div>
    <% end %>

app/views/guest_lists/new.html.erb
<% render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/scc/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class='notification is-primary global-notification'>
        <p class='notice'><%= notice%></p>
      </div> 
    <% end %>
    <% if flash[:alert]%>
      <div class='notification is-danger global-notification'>
        <p class='alert'><%= alert%></p>
      </div>
    <% end %>
    <nav class='navbar is-black'>
      <div class='navbar-brand'>
      <%= link_to root_path, class: "navbar-item" do%>  
        <h1 class='title is-3'>Private Events</h1>
      <% end %>   
      <div class='navbar-burger burger' data-target='navbarExample'>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id='navbarExample' class='navbar-menu'>
        <div class='navbar-end'>
          <div class='field is-grouped'>
            <p class='control'>
              <%= link_to "New Event", new_event_path, class: "button is-info is-inverted"%>
            </p>
            <% if user_signed_in? %>
              <p class='control'>
                <%= link_to current_user.email, edit_user_registration_path, class: 'button is-info' %>
              </p>
              <p class='control'>
                <%= link_to 'my events', user_path(current_user), class: 'button is-info' %>
              </p>
              <p>
                <%= link_to 'logout', destroy_user_session_path, method: :get, class: 'button is-info' %>
              </p>
            <% else %>
            <p class='control'>
              <%= link_to 'sign in', new_user_session_path, class: 'button is-info' %>
            </p>
            <p class='control'>
              <%= link_to 'sign up', new_user_registration_path, class: 'button is-info' %>
            </p>
            <% end %>
          </div>
        </div>

      </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/_past.html.erb
<div class='column is-half'>
  <h1 class='title is-5'>My Past Events</h1>  
  <% @past_events.each do | event | %>
  <% if event.attendees.include?(current_user) %>
    <div class='box'>
      <article class='media'>
        <div class='media-left'>
          <figure class='image is-64x64'>
            <%= gravatar_image_tag(event.creator.email, size: 64)%>
          </figure>
        </div>
        <div class='media-content'>
          <div class='content'>
            <p class='title is-3'><%= event.title %></p>
            <p class='subtitle is-5'>@<%= event.location %></p>
            <p><%= event.description %></p>
            <p class='date'><%= event.event_date %></p>
            <small>hosted by</small><br />
            <strong><%= event.creator.email %></strong><br />
            <p>attendees <%= event.attendees.count %></p>
            <%= link_to 'see event', event_path(event), method: :get, class: 'button is-info' %>
          </div>
        </div>
      </article> 
    </div>
  <% end %>  
  <% end %>
</div>  

app/views/users/_upcoming.html.erb
<div class='column is-half'>
  <h1 class='title is-5'>My Upcoming Events</h1>  
  <% @upcoming_events.each do | event | %>
  <% if event.attendees.include?(current_user) %>
    <div class='box'>
      <article class='media'>
        <div class='media-left'>
          <figure class='image is-64x64'>
            <%= gravatar_image_tag(event.creator.email, size: 64)%>
          </figure>
        </div>
        <div class='media-content'>
          <div class='content'>
            <p class='title is-3'><%= event.title %></p>
            <p class='subtitle is-5'>@<%= event.location %></p>
            <p><%= event.description %></p>
            <p class='date'><%= event.event_date %></p>
            <small>hosted by</small><br />
            <strong><%= event.creator.email %></strong><br />
            <p>attendees <%= event.attendees.count %></p>
            <%= link_to 'see event', event_path(event), method: :get, class: 'button is-info' %>
          </div>
        </div>
      </article> 
    </div>
  <% end %>  
  <% end %>
</div>

app/views/users/show.html.erb
<section class='section'>
  <div class='container'>
    <div class='columns'>
      <%= render 'upcoming' %>
      <%= render 'past' %>
    </div>
  </div>
</section>    